---

peoplesoft_base:        c:/psft
db_name:                PSFTDB
db_name_downcase:       psftdb
psft_db:
  location:             "%{hiera('psft_db_location')}"
  
ps_config_home:         c:/psft/cfg

# users
db_user:                VP1
db_connect_id:          people
access_id:              SYSADM
pia_gateway_user:       administrator
web_console_user:       system
websever_user:          PTWEBSERVER

# passwords
db_user_pwd:            VP1
db_connect_pwd:         peop1e
access_pwd:             SYSADM
pia_gateway_user_pwd:   password
web_console_pwd:        Passw0rd1
domain_conn_pwd:        Passw0rd_
webserver_pwd:          PTWEBSERVER
     
appserver_domain_name:  "%{hiera('db_name_downcase')}"
prcs_domain_name:       "%{hiera('db_name_downcase')}"
pia_domain_name:        "%{hiera('db_name_downcase')}"
pia_webprofile_name:    DEV

# The oracle_client hash is required for a fulltier to midtier change when using the PeopleTools Patch provisioner
oracle_client_location: "%{hiera('pt_location')}/oracle-client/12.1.0.2"
oracle_client:
  location: "%{hiera('oracle_client_location')}"
   
ps_home_location: "%{hiera('pt_location')}/ps_home%{hiera('tools_version')}"
ps_home:
  db_type:    "%{hiera('db_platform')}"
  unicode_db: "%{hiera('unicode_db')}"
  location:   "%{hiera('ps_home_location')}"
  remove:     true

ps_app_home:  
  location:    "%{hiera('peoplesoft_base')}/pt/ps_app_home"

db_service_name: "%{hiera('db_name')}"

tns_admin_list:
  "%{hiera('db_name')}":
    db_host: "localhost"  ## NOTE: Change this to "%{::fqdn}" if using bridged networking
    db_port:         "%{hiera('db_port')}"
    db_protocol:     TCP
    db_service_name: "%{hiera('db_service_name')}"

pia_domain_list:
  "%{hiera('pia_domain_name')}":
    os_user:               "%{hiera('domain_user')}"
    ps_cfg_home_dir:       "%{hiera('ps_config_home')}"
    gateway_user:          "%{hiera('pia_gateway_user')}"
    gateway_user_pwd:      "%{hiera('pia_gateway_user_pwd')}"
    auth_token_domain: ""  # NOTE: change this to ".%{::domain}" if using bridged networking
    webserver_settings:
      webserver_type:           "%{hiera('webserver_type')}"
      webserver_home:           "%{hiera('weblogic_location')}"
      webserver_admin_user:     "%{hiera('web_console_user')}"
      webserver_admin_user_pwd: "%{hiera('web_console_pwd')}"
      webserver_admin_port:     "%{hiera('pia_http_port')}"
      webserver_http_port:      "%{hiera('pia_http_port')}"
      webserver_https_port:     "%{hiera('pia_https_port')}"

    config_settings:
      Servers/PIA:
        ListenAddress:          0.0.0.0
      Servers/PIA/WebServer/PIA/WebServerLog/PIA: 
        LoggingEnabled:         true
        LogFileFormat:          extended
        BufferSizeKB:           0
        ELFFields:              'date time cs-method cs-uri sc-status cs-username cs(user-agent) s-ip c-ip cs(X-Forwarded-For) time-taken bytes'

    site_list:
      "%{hiera('pia_site_name')}":
        appserver_connections: "%{hiera('pia_psserver_list')}"
        domain_conn_pwd:       "%{hiera('domain_conn_pwd')}"

        webprofile_settings:
          profile_name:        "%{hiera('pia_webprofile_name')}"
          profile_user:        "%{hiera('websever_user')}"
          profile_user_pwd:    "%{hiera('webserver_pwd')}"

        report_repository_dir: "%{hiera('report_repository_dir')}"
